yolo_v3_model_path: ./public/yolo-v3-tiny-tf/FP16/yolo-v3-tiny-tf.xml
device: MYRIAD
mqtt_host: tcp://192.168.1.51:1883
mqtt_user: MQTT_USER
mqtt_password: MQTT_PASSWORD
cameras:
  - name: Front Door
    input: http://192.168.1.51:8081
    crop_top: 80
    crop_right: 150
    crop_bottom: 0
    crop_left: 0
  - name: Driveway
    input: http://192.168.1.51:8082
    crop_top: 0
    crop_right: 0
    crop_bottom: 0
    crop_left: 0
