yolo_v3_model_path: ../public/yolo-v3-tiny-tf/FP16/yolo-v3-tiny-tf.xml
device: MYRIAD
mqtt_host: tcp://192.168.1.51:1883
mqtt_user: MQTT_USER
mqtt_password: MQTT_PASSWORD
tracked_classes:
  - person
detection_threshold: 0.5
cameras:
  - name: Front Door
    input: http://192.168.1.51:8081
  - name: Driveway
    input: http://192.168.1.51:8082
